language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.10"
before_install:
  - perlbrew install-cpanm -f
install:
  - cpanm git://github.com/kan/coveralls-perl.git
script: perl Build.PL && ./Build build && ./Build testcover
after_success:
  - "cover -report coveralls"

